apiVersion: apps/v1
kind: Deployment
metadata:
  name: bangokit-string-service
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: string-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: string-service
    spec:
      containers:
        - name: string-service
          image: <VERSION>
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gitlabregkey
---
apiVersion: v1
kind: Service
metadata:
  name: string-service-service
spec:
  selector:
    app: string-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: string-service
  annotations:
    kubernetes.io/ingress.class: elb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /string-service
        backend:
          serviceName: string-service-service
          servicePort: 80
